Add a.out to .gitignore
petarmaric/pjisp-assignment-template pull request #1
Opened 2019-10-27 18:02 UTC by JRubics

2019-10-27 20:48 UTC, petarmaric requested changes
As stated in `README.rst`, please add yourself to `CONTRIBUTORS`.

2019-10-28 18:36 UTC, petarmaric approved these changes

2019-10-28 18:38 UTC, merged

2019-10-28 20:13 UTC, JRubics commented
Nisam mislila da mene dodas u contributore nego a.out u gitignore xD

On Mon, 28 Oct 2019, 19:38 Petar Marić, <notifications@github.com> wrote:

> Merged #1 <https://github.com/petarmaric/pjisp-assignment-template/pull/1>
> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/petarmaric/pjisp-assignment-template/pull/1?email_source=notifications&email_token=AFNOECVQPWR4LOI3AC2A4E3QQ4WRDA5CNFSM4JFSXWD2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUPSC3WA#event-2749640152>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFNOECWCUWWTSFYBWEIDTCLQQ4WRDANCNFSM4JFSXWDQ>
> .
>

2019-10-28 20:17 UTC, petarmaric commented
Give credit where credit due :1st_place_medal: